name: Build Android App

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: '9.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build the Android app
      run: dotnet build --configuration Release

    - name: Publish the Android app
      run: dotnet publish -c Release -o ./output

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-app
        path: ./output
