name: Build Android App

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: '9.0.x'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME
        mkdir -p $HOME/android-sdk/cmdline-tools
        mv $HOME/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
        yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses
        sdkmanager --sdk_root=$HOME/android-sdk "platforms;android-35" "platform-tools"

    - name: Install Android workload
      run: dotnet workload install android

    - name: Install dependencies
      run: dotnet restore

    - name: Build the Android app
      run: dotnet build --configuration Release

    - name: Publish the Android app
      run: dotnet publish -c Release -o ./output

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-app
        path: ./output